name: Github Actions Test2
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - run: echo "${{github.action}}"
      - run: echo "${{github.ref}}"
      - run: echo "${{github.repository}}"
